### ISSUE TITLE
Please disable scroll propagation

### ISSUE THREAD

**Issue by drheinheim** [yigityuce/Leaflet.Control.Custom#1]
Great plugin. Please add the following (it's not worth creating a new branch just for this):

`L.DomEvent.disableScrollPropagation(this.container);`

Thanks!

Fyi, I'm using this with a long select, where scrolling is needed.

**Comment by yigityuce** [comment]
Hi @rheinheimer , 

Scroll propagation stop is added https://github.com/yigityuce/Leaflet.Control.Custom/commit/7b4c90888773fc8041f182b0b6e3e6c36c419505
