### ISSUE TITLE
set z-index

### ISSUE THREAD

**Issue by drheinheim** [yigityuce/Leaflet.Control.Custom#2]
Another issue: is it possible to force the z-index to ensure any dropdowns are above other controls? I had a select (Bootstrap Selectpicker, to be precise) that remained below other controls. I had a hard time doing this, and ended up with a CSS hack by trial-and-error. I'll look around at some other controls for a solution.

**Comment by yigityuce** [comment]
Hi @rheinheimer ,

I assume you are using [this](https://github.com/silviomoreto/bootstrap-select) selectpicker. I generally use it too. It uses "[dropdown-menu](https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css#L3520)" class as defined at [bootstrap.css](https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css) file and it sets z-index to 1000 for dropdowns. So this is a css design and it should be handled by user. If you set other controls' z-indexes less than 1000 or override the "dropdown-menu" class z-index value to max. (ex: 99999999)  there will be no problem about ordering.
